-- AlterTable
ALTER TABLE "ExifData" ALTER COLUMN "focalLength" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Photo" ALTER COLUMN "filename" DROP NOT NULL,
ALTER COLUMN "width" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "fileSize" DROP NOT NULL,
ALTER COLUMN "mimeType" DROP NOT NULL,
ALTER COLUMN "title" DROP NOT NULL;
